name: noti
description: "task and note manager app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  animations: ^2.0.11
  shared_preferences: ^2.3.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3
  photo_manager_image_provider: ^2.1.1
  photo_manager: ^3.0.0
  camera: ^0.11.0+1
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.2
  webview_flutter: ^4.8.0
  csshadow: ^0.0.2
  flutter_localization: ^0.2.1
  permission_handler: ^10.4.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  audioplayers: ^6.1.0
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/sounds/sound.wav

#todo: remove before publish:
    - assets/data/tasks_notes.json



  fonts:
    - family: NotiSystemIcons
      fonts:
        - asset: assets/fonts/NotiSystemIcons.ttf

