import 'package:flutter/material.dart';
import 'package:noti/models/menu_model/category_icon_model.dart';

class CategoryIconsList {
  List<CategoryIconModel> iconsList = [
    CategoryIconModel(icon:Icons.shopping_cart,name:"cart" ,isPicked: false),
    CategoryIconModel(icon:Icons.phone,name:"phone" ,isPicked: false),
    CategoryIconModel(icon: Icons.edit, name: "edit", isPicked: false),
    CategoryIconModel(icon: Icons.people, name: "people", isPicked: false),
    CategoryIconModel(icon: Icons.search, name: "search", isPicked: false),
    CategoryIconModel(icon: Icons.computer, name: "computer", isPicked: false),
    CategoryIconModel(icon: Icons.access_alarm, name: "alarm", isPicked: false),
    CategoryIconModel(icon: Icons.favorite, name: "favorite", isPicked: false),
    CategoryIconModel(icon: Icons.insert_drive_file, name: "file", isPicked: false),
    CategoryIconModel(icon: Icons.mail, name: "mail", isPicked: false),
    CategoryIconModel(icon: Icons.restaurant, name: "restaurant", isPicked: false),
    CategoryIconModel(icon: Icons.fitness_center, name: "fitness", isPicked: false),
    CategoryIconModel(icon: Icons.cake, name: "cake", isPicked: false),
    CategoryIconModel(icon: Icons.free_breakfast, name: "breakfast", isPicked: false),
    CategoryIconModel(icon: Icons.comment, name: "comment", isPicked: false),
    CategoryIconModel(icon: Icons.colorize, name: "colorize", isPicked: false),
    CategoryIconModel(icon: Icons.camera_alt, name: "camera", isPicked: false),
    CategoryIconModel(icon: Icons.cast_for_education, name: "education", isPicked: false),
    CategoryIconModel(icon: Icons.work, name: "work", isPicked: false),
    CategoryIconModel(icon: Icons.weekend, name: "weekend", isPicked: false),
    CategoryIconModel(icon: Icons.home, name: "home", isPicked: false),
    CategoryIconModel(icon: Icons.directions_car, name: "car", isPicked: false),
    CategoryIconModel(icon: Icons.directions_bus, name: "bus", isPicked: false),
    CategoryIconModel(icon: Icons.thumbs_up_down, name: "thumbs", isPicked: false),
    CategoryIconModel(icon: Icons.wb_cloudy, name: "cloudy", isPicked: false),
    CategoryIconModel(icon: Icons.wb_sunny, name: "sunny", isPicked: false),
    // Icons.shopping_cart,
    // Icons.local_phone,
    // Icons.edit,
    // Icons.people,
    // Icons.search,
    // Icons.computer,
    // Icons.access_alarm,
    // Icons.favorite,
    // Icons.insert_drive_file,
    // Icons.mail,
    // Icons.shopping_cart,
    // Icons.restaurant,
    // Icons.fitness_center,
    // Icons.cake,
    // Icons.free_breakfast,
    // Icons.comment,
    // Icons.colorize,
    // Icons.camera_alt,
    // Icons.cast_for_education,
    // Icons.work,
    // Icons.weekend,
    // Icons.home,
    // Icons.directions_car,
    // Icons.directions_bus,
    // Icons.search,
    // Icons.thumbs_up_down,
    // Icons.wb_cloudy,
    // Icons.wb_sunny,
  ];
}
